* nginx folder

diff --git a/vm-deploy b/vm-deploy
--- a/vm-deploy
+++ b/vm-deploy
@@ -33,6 +33,13 @@ if ! [[ -f /app/servers.env ]]; then
 	exit 1
 fi
 
+if ! [[ -f /app/image.tar.gz ]]; then
+	echo "ERROR: el archivo /app/image.tar.gz no existe, favor consulte la documentacion."
+	exit 1
+else
+	mv -f /app/image.tar.gz /var/www/html/
+fi
+
 while read -r ip puerto usuario clave password vmid nombre url; do
 	echo "$ip", "$puerto", "$usuario", "$password", "$vmid", "$nombre", "$url"
 	if [[ "$puerto" == "22" ]]; then
